### ISSUE TITLE
where solution file?

### ISSUE THREAD

**Issue by Lander-P** [stijnv18/pvp-v21#1]
Best realese ever

**Comment by stijnv18** [comment]
no

**Comment by Lander-P** [comment]
![no-body-asked-man-talking-to-wall](https://user-images.githubusercontent.com/44321266/208904816-91fb8fe1-1fff-4ba4-8bae-73b107dd3ae9.gif)

**Comment by stijnv18** [comment]
Ban

**Comment by stijnv18** [comment]
+ratio

**Comment by Lonely-Potato** [comment]
+skill issue

**Comment by stijnv18** [comment]
+bad
